development:
  adapter: postgresql
  encoding:  utf-8
  database: fruehlance_development
  pool: 5
  username: heel
  host: localhost

test:
  adapter: postgresql
  encoding:  utf-8
  database: fruehlance_test
  pool: 5
  username: heel
  host: localhost